{% set name = "pyotp" %}
{% set version = "2.2.7" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "be0ffeabddaa5ee53e7204e7740da842d070cf69168247a3d0c08541b84de602" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyotp

about:
  home: https://github.com/pyauth/pyotp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python One Time Password Library
  description: "PyOTP - The Python One-Time Password Library. PyOTP is a Python library for generating and verifying one-time passwords. It can be used to\
    \ implement two-factor (2FA) or multi-factor (MFA) authentication methods in web applications and in other systems that require users to log in. "
  doc_url: https://pyotp.readthedocs.io/
  dev_url: https://github.com/pyauth/pyotp

extra:
  recipe-maintainers:
    - kalling
    - smithsp
