travis:
  secure:
    BINSTAR_TOKEN: nK0ziZIC759mda4iZpRK4U8JGqqIxWaFcuDG61Vj2nUqyvxAi5EwKSci3/toXTv5IudHHfE5rXLn8bIx7imhogBpDE/wYcaFZn2F0qqPEbac+G2y4yKcZK6rVR96XBCmhOVCFXziBdPYHyyJ0dHW+3n94Cm9eECcmvdB9ISNZ/AFu6P9ykHfGG0fMYMLwav4S0hxTsYpImuAmY2xjiFSphJ0MdIzOtLkXzb3srddjU7P7jtnh+XO9+XrdgBsCavSPNssTCw3snmk1kE4Xgbds+LyKKr8LYUdBCTz7XSai3+VXv2nzLC6WtkPpB8AEDjM0Upwu4dz4OGfORgBSxeaZ7nuncx85qoXjLOKgNkwCyUfHXdQz8j5hiey5N/PdilWXi3RNqZGb0mbDQd7jdTkwDmnFvphEb3Txmw/8Ai8uH1TDKhtZYWK2g2sUkcerhGlQD/p5sZvdvMFIFfGdNCkIRfMPILlPFrHYMRMiwTehxHqClFBBtDHlURaq6Wq6pPm/PVoeqE5QHmODrWYSlMTl38XkOt2woYFD1dEGvHGsdfTWZ3mbxmYJYtZwhzYoLW5bMlEbhiyV6HMXFDSoQH9OxzyaV7t9X5icLGeu3MBLycKYX9a9h5AT8isqfMe7UNdpdWOKxpe6yGVoB37MoBDnLZB15sE5baDLdSzD1tw9+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
